---
- name: Deploy database
  hosts: appdb.example.com
  become_user: root
  roles:
    - name: Install and configure firewall
      role: firewall
      vars:
        firewall_services:
          - mysql
    - name: database deployment
      role: mysqldb


- name: Deploy haproxy
  hosts: frontend.example.com
  roles:
    - name: Install and configure firewall
      role: firewall
      vars:
        firewall_services:
          - http
        firewall_tcp_ports:
          - 5000
    - name: frontend deployment
      role: haproxy


- name: Deploy apache
  hosts: app1.example.com,app2.example.com
  roles:
    - name: Install and configure firewall
      role: firewall
      vars:
        firewall_services:
          - http
        firewall_tcp_ports:
          - 8080
    - name: application deployment
      role: apache
