---
- name: Deploy database
  hosts: appdb.example.com
  roles:
    - name: Install and configure firewall
      role: firewall
      vars:
        firewall_services:
          - mysql
    - name: database deployment
      role: mysqldb


- name: Deploy haproxy
  hosts: 192.168.50.25
  roles:
    - name: Install and configure firewall
      role: firewall
      vars:
        firewall_services:
          - http
        firewall_tcp_ports:
          - 5000
    - name: frontend deployment
      role: haproxy


- name: Deploy apache
  hosts: 192.168.50.182,192.168.50.141
  roles:
    - name: Install and configure firewall
      role: firewall
      vars:
        firewall_services:
          - http
        firewall_tcp_ports:
          - 8080
    - name: application deployment
      role: apache
