---
- name: Create OpenStack Instances
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    guid: "{{ lookup('env','GUID') }}"
  tasks:
    - name: Include Instance variables
      include_vars: instances_vars.yml

    - name: Create Instance
      openstack.cloud.server:
        cloud: "3527-project"
        name: "{{ item.name }}"
        image: "{{ item.image }}"
        key_name: "{{ item.keypair }}"
        flavor: "{{ item.flavor }}"
        security_groups: "{{ item.security_group }}"
        auto_ip: no
        wait: no
        nics:
          - net-name: "{{ item.internal_network }}"
        meta:
          AnsibleGroup: "AnsibleGroup={{item.metadata.AnsibleGroup}},deployment_name={{item.metadata.deployment_name}}"
          type: "{{ item.metadata.type }}"
        userdata: |
          #!/bin/bash
          echo "nameserver 192.168.50.158" > /etc/resolv.conf
        state: present
      register: servers
      loop: "{{ instances }}"
      async: 7200
      poll: 0
 
