---
- name: Create OpenStack Instances
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    guid: 3527
  tasks:
    - name: Include Instance variables
      include_vars: instances_vars.yml

    - name: Create Instance....
      openstack.cloud.server:
        devstack: "{{ guid }}-project"
        name: "{{ instance.name }}"
        image: "{{ instance.image }}"
        key_name: "{{ instance.keypair }}"
        flavor: "{{ instance.flavor }}"
        security_groups: "{{ instance.security_group }}"
        auto_ip: no
        wait: yes
        nics:
          - net-name: "{{ instance.internal_network }}"
        meta: "AnsibleGroup={{instance.metadata.AnsibleGroup}},deployment_name={{instance.metadata.deployment_name}}"
        userdata: |
          #!/bin/bash
          echo "nameserver 192.168.50.158" > /etc/resolv.conf 
        state: present
      loop: "{{ instances }}"
      loop_control:
        loop_var: instance
